name: stocks_application
description: A stock application
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  dio: ^5.1.1
  get: ^4.6.5
  hive_flutter: ^1.1.0
  new_gradient_app_bar: ^0.1.4
  material_floating_search_bar: ^0.3.7
  async: ^2.10.0
  fl_chart: ^0.62.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  search_page: ^2.3.0
  google_fonts: ^3.0.1



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true
  assets:
    - assets/design/images/vuesax-linear-star.png
    - assets/design/images/share-24-outline.png
    - assets/design/images/vuesax-bold-copy.png
    - assets/design/images/vuesax-twotone-card-receive.png
    - assets/design/images/down-arrow-24-outline.png
    - assets/design/images/text-input.png
    - assets/design/images/container.png
    - assets/design/images/up-arrow-24-outline.png
    - assets/design/images/vuesax-linear-messages-2.png
    - assets/design/images/card.png
    - assets/design/images/container-pzU.png
    - assets/design/images/container-w9A.png
    - assets/design/images/container-KRa.png
    - assets/design/images/image-8.png
    - assets/design/images/vertical-container.png
    - assets/design/images/vuesax-linear-arrow-left.png
    - assets/design/images/card-4Cp.png
    - assets/design/images/image-7.png
    - assets/design/images/down-arrow-24-outline-ci4.png
    - assets/design/images/image-4.png
    - assets/design/images/vertical-container-9Ex.png
    - assets/design/images/image-4-LPA.png
    - assets/design/images/vertical-container-QYG.png
    - assets/design/images/vuesax-linear-arrow-left-8UG.png
    - assets/design/images/group-1.png
    - assets/design/images/image-5.png
    - assets/design/images/container-8dN.png
    - assets/design/images/text-input-Se4.png
    - assets/design/images/text-input-1SG.png
    - assets/design/images/card-P3W.png
    - assets/design/images/vertical-container-LzL.png
    - assets/design/images/down-arrow-24-outline-6yW.png
    - assets/design/images/vector.png
    - assets/design/images/container-5F6.png
    - assets/design/images/vector-NX2.png
    - assets/design/images/frame-62.png
    - assets/design/images/container-AYg.png
    - assets/design/images/vertical-container-J96.png
    - assets/design/images/card-shz.png
    - assets/design/images/vertical-container-CJC.png
    - assets/design/images/vertical-container-x2U.png
    - assets/design/images/vector-BZS.png
    - assets/design/images/up-arrow-24-outline-8Fi.png
    - assets/design/images/vertical-container-WKS.png
    - assets/design/images/text-input-PfN.png
    - assets/design/images/dai.png
    - assets/design/images/card-NbA.png
    - assets/design/images/vuesax-linear-arrow-left-Po6.png
    - assets/design/images/down-arrow-24-outline-wEG.png
    - assets/design/images/container-R2x.png
    - assets/design/images/vertical-container-5Fv.png
    - assets/design/images/container-art.png
    - assets/design/images/card-ZEG.png
    - assets/design/images/vector-x9v.png
    - assets/design/images/down-arrow-24-outline-N7A.png
    - assets/design/images/setting-24-outline.png
    - assets/design/images/down-arrow-24-outline-XRJ.png
    - assets/design/images/down-arrow-24-outline-iu6.png
    - assets/design/images/vuesax-linear-messages-2-SCp.png
    - assets/design/images/text-input-p4x.png
    - assets/design/images/vector-HA8.png
    - assets/design/images/vector-qxL.png
    - assets/design/images/image-6.png
    - assets/design/images/vector-yYk.png
    - assets/design/images/card-8Re.png
    - assets/design/images/vertical-container-J5E.png
    - assets/design/images/card-5Lt.png
    - assets/design/images/up-arrow-24-outline-qqr.png
    - assets/design/images/vector-Dhz.png
    - assets/design/images/left-alignment-24-outline.png
    - assets/design/images/vertical-container-Nqn.png
    - assets/design/images/vertical-container-khv.png
    - assets/design/images/vertical-container-XTn.png
    - assets/design/images/container-WBJ.png
    - assets/design/images/container-gLg.png
    - assets/design/images/icon-outline-plus-sm.png
    - assets/design/images/vertical-container-dmi.png
    - assets/design/images/vector-pBz.png
    - assets/design/images/vector-CK2.png
    - assets/design/images/auto-group-yrmy.png
    - assets/design/images/container-MSp.png
    - assets/design/images/left-alignment-24-outline-7wn.png
    - assets/design/images/vuesax-twotone-card-send.png
    - assets/design/images/vertical-container-sg4.png
    - assets/design/images/setting-24-outline-SjA.png
    - assets/design/images/vector-DV2.png
    - assets/design/images/button-container.png
    - assets/design/images/down-arrow-24-outline-kjz.png
    - assets/design/images/vector-iic.png

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
        - asset: fonts/Roboto-Thin.ttf
        - asset: fonts/Roboto-Light.ttf
          style: italic


#  fonts:
#    - family: Roboto
#        fonts:
#          - asset: fonts/Roboto-Regular.ttf
#          - asset: fonts/Roboto-Bold.ttf
#          - asset: fonts/Roboto-Thin.ttf
#          - asset: fonts/Roboto-Light.ttf
#          - asset: fonts/Roboto-Black.ttf
#             style: italic
